# Generated by Django 2.1.4 on 2018-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(unique_for_date='pulish_data')),
                ('content', models.TextField()),
                ('pulish_data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': '',
                'ordering': ('-pulish_data',),
                'managed': True,
            },
        ),
    ]
